global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "dotnet-app"
    static_configs:
      - targets: ["dotnet-api"]

  - job_name: 'aspnetcore'
    static_configs:
      - targets: ['dotnet-api']