global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "dotnet-app"
    static_configs:
      - targets: ["dotnet-api"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
